driver:
  name: dokken
  chef_version: 14.11.21

transport:
  name: dokken

provisioner:
  name: dokken

platforms:

  - name: aws-linux
    driver:
      pid_one_command: /sbin/init
      image: dokken/amazonlinux
      intermediate_instructions:
        # When running outside jenkins provide assumed IAM aws creds
        <% if ENV['USER'] != 'jenkins' %>
        - ENV AWS_SHARED_CREDENTIALS_FILE=/.aws/credentials
        <% end %>
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        # When running outside jenkins provide assumed IAM aws creds
        # Note I'm seein odd behaviour in test kitchen locally where it takes
        # multiple attempts for it to manage to set up these volumes as it's
        # just local I'm working around it for by converged until it sucseeds
        <% if ENV['USER'] != 'jenkins' %>
        - <%= ENV['HOME'] %>/.aws:/.aws:ro
        <% end %>

  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      privileged: true
      pid_one_command: /bin/systemd
      intermediate_instructions:
        # Note that kitchen-dokken will only run this once when it first pulls
        # down the image, if you have this cached and it's old you'll probably
        # get errors from apt
        - RUN apt-get update
        # When running outside jenkins provide assumed IAM aws creds
        <% if ENV['USER'] != 'jenkins' %>
        - ENV AWS_SHARED_CREDENTIALS_FILE=/.aws/credentials
        <% end %>
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        # When running outside jenkins provide assumed IAM aws creds
        # Note I'm seein odd behaviour in test kitchen locally where it takes
        # multiple attempts for it to manage to set up these volumes as it's
        # just local I'm working around it for by converged until it sucseeds
        <% if ENV['USER'] != 'jenkins' %>
        - <%= ENV['HOME'] %>/.aws:/.aws:ro
        <% end %>

  - name: aws-linux-2
    driver:
      image: dokken/amazonlinux-2
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        # When running outside jenkins provide assumed IAM aws creds
        <% if ENV['USER'] != 'jenkins' %>
        - ENV AWS_SHARED_CREDENTIALS_FILE=/.aws/credentials
        <% end %>
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        # When running outside jenkins provide assumed IAM aws creds
        # Note I'm seein odd behaviour in test kitchen locally where it takes
        # multiple attempts for it to manage to set up these volumes as it's
        # just local I'm working around it for by converged until it sucseeds
        <% if ENV['USER'] != 'jenkins' %>
        - <%= ENV['HOME'] %>/.aws:/.aws:ro
        <% end %>

suites:
  - name: default
    run_list:
      - recipe[jlaws::default]
  - name: instance-status
    run_list:
      - recipe[test-jlaws::default]
  - name: secrets-manager
    run_list:
      - recipe[test-jlaws::secrets-manager]
